create table if not exists user (
  id int generated by default as identity(start with 1) not null,
  username varchar(255) not null,
  password varchar(255) not null,
  primary key (id)
);
create table if not exists roles (
  id int generated by default as identity(start with 1) not null,
  role_name varchar(255) not null,
  primary key (id)
);
create table if not exists unit_type (
  id int generated by default as identity(start with 1) not null,
  unit_type_name varchar(255) not null,
  primary key (id)
);
create table if not exists stat_category (
  id int generated by default as identity(start with 1) not null,
  stat_category_name varchar(255) not null,
  primary key (id)
);
create table if not exists goal (
  id int generated by default as identity(start with 1) not null,
  title varchar(255) not null,
  goal_value numeric not null,
  goal_logic varchar(255) not null,
  goal_completed boolean default false not null,
  primary key (id)
);
create table if not exists stat (
  id int generated by default as identity(start with 1) not null,
  stat_name varchar(255) not null,
  unit_type_id bigint not null,
  stat_category_id bigint not null,
  user_id bigint not null,
  primary key (id),
  foreign key (unit_type_id)
  references unit_type (id),
  foreign key (stat_category_id)
  references stat_category (id),
  foreign key (user_id)
  references user (id)
);
create table if not exists progress (
  id int generated by default as identity(start with 1) not null,
  stat_id bigint not null,
  progress_value numeric not null,
  progress_timestamp timestamp default current_timestamp not null,
  primary key (id),
  foreign key (stat_id)
  references stat (id)
);
create table if not exists goal_stat (
  id int generated by default as identity(start with 1) not null,
  goal_id bigint not null,
  stat_id bigint not null,
  primary key (id),
  foreign key (goal_id)
  references goal (id),
  foreign key (stat_id)
  references stat (id)
);
create table if not exists user_role (
  id int generated by default as identity(start with 1) not null,
  user_id bigint not null,
  role_id bigint not null,
  primary key (id),
  foreign key (user_id)
  references user (id),
  foreign key (role_id)
  references roles (id)
);