version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: 'habitGoals-postgres'
    environment:
      - POSTGRES_PASSWORD=Password111
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
