version: '3.3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: 'habitStats-postgres'
    environment:
      - POSTGRES_PASSWORD=Password111
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

