spring:
  application:
    name: @artifactId@
  config:
    activate:
      on-profile: dev

server:
  port: 8085

---
spring:
  config:
    name: dev
  datasource:
    url: jdbc:h2:mem:mik
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    web: debug
    org:
      hibernate: info
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
---
spring:
  config:
    name: dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: Password111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.postgresqldialect
    defer-datasource-initialization: true
  sql:
     init:
       mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    web: debug
    org:
      hibernate: info
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
---
spring:
  config:
    name: prod